### ISSUE TITLE
Can not find any suitable profile id for firefox type 0

### ISSUE THREAD

**Issue by chriskempson** [zefr0x/foxmarks#2]
Running `firemarks bookmarks` produces the following error:

`thread 'main' panicked at 'Can not find any suitable profile id for firefox type 0', src/database.rs:57:17`

My `profile.ini`:

```
[Profile3]
Name=default-release
IsRelative=1
Path=Profiles/xxxxxxxx.default-release

[Profile2]
Name=Japanese
IsRelative=1
Path=Profiles/xxxxxxxx.default-release

[Profile1]
Name=Personal
IsRelative=1
Path=profile-XXXXXXXXXXXXXXXXXXXXXXXXXX
Default=1

[Profile0]
Name=Work
IsRelative=1
Path=Profiles/xxxxxxxx.Work

[General]
StartWithLastProfile=1
Version=2

[Install1F42C145FFDD4120]
Default=Profiles/xxxxxxxx.Work
Locked=1

[Install2656FF1E876E9973]
Default=profile-XXXXXXXXXXXXXXXXXXXXXXXXXX
Locked=1
```

Firefox version: `116.0.2`.

**Comment by zefr0x** [comment]
Since you are using a custom profile as your default one, you should use the `--profile-id` option like this:

```
foxmarks --profile-id <ID> bookmarks
```

The ID would be the `Path` value from a `ProfileX` entrie, for example `Profiles/xxxxxxxx.default-release` for:
```
[Profile3]
Name=default-release
IsRelative=1
Path=Profiles/xxxxxxxx.default-release
```

I should've written an explanation in README.md 😅 and improve the error message.

**Comment by chriskempson** [comment]
Oh thanks very much for that! I did experiment with the `--profile-id` option but didn't realise it was the value of path that was the ID sorry 😅

**Comment by zefr0x** [comment]
> I did experiment with the `--profile-id` option but didn't realise it was the value of path that was the ID

Thanks for the feedback, I will change it to `--profile-path` in the next major release 👍

I wasn't fully aware of how profiles work when I chose the name.
